name: Deploy to EC2

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}  # Store your EC2 private SSH key in GitHub Secrets

    - name: SSH into EC2 and check if repo exists, then clone or pull
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@3.87.184.172 << 'EOF'
        if [ -d "/var/test" ]; then
          echo "Repository exists. Pulling latest changes..."
          cd /var/test
          git pull origin main
        else
          echo "Repository does not exist. Cloning repository..."
          git clone git@github.com:HimanshuGupta08/test-repo.git /var/test
        fi
        EOF
